version: '3'

vars:
  GOLANGCI_LINT_VERSION: 'v2.1.6'
  GOLANG_CI: "docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} golangci-lint"
  IMAGE_NAME: "reportportal-mcp-server"
dotenv: ['.env']
tasks:
  fmt:
    desc: "Runs formatter"
    cmd: "{{.GOLANG_CI}} fmt ./..."
  lint:
    desc: "Runs GolangCI linter"
    cmd: "{{.GOLANG_CI}} run ./..."

  docker:build:
    desc: "Builds docker image"
    cmd: "docker build -t {{.IMAGE_NAME}} ."

  inspector:
    desc: "Runs inspector"
    deps: [docker:build]
    cmd: >
      npx @modelcontextprotocol/inspector -- docker run -i --rm -e "RP_API_TOKEN=$RP_API_TOKEN" -e "RP_PROJECT=$RP_PROJECT" -e "RP_HOST=$RP_HOST" reportportal-mcp-server