version: '3'

vars:
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GOLANG_CI: "docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} golangci-lint"
  IMAGE_NAME: "reportportal-mcp-server"

tasks:
  fmt:
    desc: "Runs formatter"
    cmd: "{{.GOLANG_CI}} fmt ./..."
  lint:
    desc: "Runs GolangCI linter"
    cmd: "{{.GOLANG_CI}} run ./..."

  docker:build:
    desc: "Builds docker image"
    cmd: "docker build -t {{.IMAGE_NAME}} ."